# -*- coding: utf-8 -*-
"""Emisiones de CO2 per cápita..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fVLhrM726hU7Q6sXbM1_XMD950XlQKsm
"""

# Este será mi script para visualización
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt
import seaborn as sns


df_countries = pd.read_excel("/content/API_EN.ATM.CO2E.PC_DS2_es_excel_v2_6300249.xls",sheet_name="Metadata - Countries")

df_index = pd.read_excel("/content/API_EN.ATM.CO2E.PC_DS2_es_excel_v2_6300249.xls",sheet_name="Data", skiprows= 3 )


#¿Cuál es el valor promedio del indicador seleccionado entre los países de América Latina en el año 2020?

america_latina = df_countries[df_countries["Region"] == "América Latina y el Caribe (excluido altos ingresos)"]

df_index.merge(america_latina,on= ["Country Name" , "Country Code"],how = "left")

latina =america_latina.merge(df_index,on= ["Country Name" , "Country Code"],how = "left")

df_melted = latina.melt(id_vars=['Country Code'], var_name='Anio', value_name='Valor del Indicador')

df_2020 = df_melted[df_melted['Anio'] == '2020']
# Calcular la media de la columna 'Valor del Indicador'
media_2020 = df_2020['Valor del Indicador'].mean()

# Imprimir la media para el año 2020
print(f"La media de Emisiones de CO2 per cápita. para América Latina en 2020 es: {media_2020}")

#¿Cómo ha evolucionado este indicador a lo largo del tiempo en América Latina?

df_melted['Valor del Indicador'] = pd.to_numeric(df_melted['Valor del Indicador'], errors='coerce')
df_melted = df_melted.dropna(subset=['Valor del Indicador'])
plt.figure(figsize=(15, 15))
sns.lineplot(data=df_melted, x='Anio', y='Valor del Indicador', hue='Country Code', ci=None)
plt.title('Evolución de Emisiones de CO2 per cápita en América Latina a lo largo del tiempo')
plt.xlabel('Año')
plt.ylabel('Emisiones de CO2 per cápita.')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

#¿Cómo es el mapa de correlación entre los últimos 5 años de datos disponibles para los países de América Latina?

# Filtrar datos para los últimos 5 años
ultimos_5_anios = df_melted[df_melted['Anio'].astype(int) >= 2016]

# Calcular la matriz de correlación
matriz_correlacion = ultimos_5_anios.pivot_table(index='Country Code', columns='Anio', values='Valor del Indicador', aggfunc='mean').corr()

# Graficar el mapa de correlación
plt.figure(figsize=(12, 10))
sns.heatmap(matriz_correlacion, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Mapa de correlación entre los últimos 5 años de datos en América Latina')
plt.show()